apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
    mongo-root-username: dXNlcm5hbWU=
    mongo-root-password: cGFzc3dvcmQ=
    

# apiVersion: v1
# kind: Secret
# metadata:
#   name: mongo-secret
# type: Opaque
# data:
#   username: bW9uZ291c2Vy  # base64 for: mongouser
#   password: cGFzc3dvcmQ=  # base64 for: password